POST https://animediary-backend-e3g9pjo0x-bibhutis-projects-bfa6b876.vercel.app/pages/api/userapi
Content-Type: application/json

{
  "name": "Test User",
  "profileurl": "https://example.com/profile.jpg",
  "email": "testuser@example.com",
  "clerkId": "123456"
}
